### ISSUE TITLE
Is SQLAlchemy in use?

### ISSUE THREAD

**Issue by chick0** [Stella-IT/XenXenXenSe#67]
MySQL module was deleted at 9ca528857138ffdc032a1dd43eec0fd0ebb3e8fd .

Is it still using on this system?

**Comment by Alex4386** [comment]
This was initially added to the dependencies due to implementation of MySQL based Cache.

But due to deprecation of the cache, It seems it no longer requires mySQL at the moment.

**Comment by Alex4386** [comment]
pinging @zeroday0619 for future plans for cache implementation

**Comment by zeroday0619** [comment]
@chick0 I decided there was no reason to cache. We will be removing related dependent libraries soon.

**Comment by Alex4386** [comment]
@zeroday0619 any updates?
